name: Update CodeChef Rating

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch CodeChef Rating from API
      - name: Fetch CodeChef Rating
        id: fetch-rating
        run: |
          username="abubakar119147" # Replace this with your CodeChef username
          response=$(curl -s https://competitive-coding-api.vercel.app/api/codechef/$username)
          rating=$(echo "$response" | jq -r '.rating')
          echo "rating=$rating" >> $GITHUB_ENV

      # Step 3: Update README.md
      - name: Update README.md with CodeChef Rating
        run: |
          sed -i "s/CodeChef Rating: [0-9]*/CodeChef Rating: $RATING/" README.md

      # Step 4: Commit Changes
      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update CodeChef Rating to $RATING" || echo "No changes to commit"
          git push
